### ISSUE TITLE
H1 in appropriate landmark violation

### ISSUE THREAD

**Issue by kaplan** [opena11y/ainspector-for-firefox#39]
This is a great tool! I'm struggling with a page where I'm almost certain the H1 is in the main, but the tool says it's not. This is a WordPress site and the h1 is in the database, then includes on the page with a PHP while loop. 

This is the Selected Element with a Violation
<img width="1508" alt="Screen Shot 2022-08-26 at 9 29 38 AM" src="https://user-images.githubusercontent.com/432395/186927688-a11daa79-4aa6-4e4a-af41-14d0b3f7e534.png">

Action
Move H1 element into an appropriate landmark. (This may require creating an additional landmark.)

Tag Name
h1

Visibility
graphical rendering: visible
assistive technology: visible

Accessible Name
text: none
source: none

I downloaded the JSON and I wondered if the `"ordinal_position": 37,` might reference the order of the loading. I can share a link if that helps.

**Comment by jongund** [comment]
Do you have the URL to the website?

**Comment by jongund** [comment]
No response so close issue
