### ISSUE TITLE
AInspector not working with Angular sites

### ISSUE THREAD

**Issue by SOM-fermonte** [opena11y/ainspector-for-firefox#40]
As the title says, navigating to an Angular site causes the add-on to never complete its evaluation. The Export and Rerun Evaluation buttons are greyed out and the Summary Title says Updating...

To replicate:
Firefox 105.0.2 (latest as of this posting)
Install add-on
Navigate to angular.io, material.angular.io, or even github.com
![image](https://user-images.githubusercontent.com/24226837/194107354-62de9ccc-aee5-4652-adbd-720088fce9f0.png)

**Comment by jongund** [comment]
@SOM-fermonte 
Version 2.1 has been released that hopefully fixes the problem, can you please test and let me know?

**Comment by SOM-fermonte** [comment]
Follow-up on this. All our testing is going well. Thanks for your work on this!

Closing the issue as resolved.
