### ISSUE TITLE
H1 must match part of the TITLE violation question

### ISSUE THREAD

**Issue by pczarn2** [opena11y/ainspector-for-firefox#57]
Good morning, the IA is marking my page as violation for H1 must match part of the TITLE, for the following code. I think the dash immediately after the work Authorization in the title is throwing the error. Can this be fixed in AInspector or is this something I need to fix in my application? 

Here is the relevant code of the page:

		<head>
		  <meta charset="utf-8">
		  <title>Request Authorization-SVN Bulk Commit</title>
		  <meta name="viewport" content="width=device-width, initial-scale=1">
		  
		  ...

                </head>

		<body>
		...
		    <main id="main">
		

		<h1>Request Authorization</h1>
                ...
      
               </body>
</html>

**Comment by jongund** [comment]
Thanks for the feedback, I will make this change in the Evaluation Library,

**Comment by jongund** [comment]
The special character issue in titles is fixed in the next version of the Evaluation Library, I will update AInspector sometime next week.  Thanks again for your feedback.

**Comment by jongund** [comment]
Fixed in release 1.99.6
