### ISSUE TITLE
fix for SC 2.5 , data table rows/cells being treatred as widgets, bad grammar in panel messages

### ISSUE THREAD

**Issue by ozross** [opena11y/ainspector-for-firefox#60]
The current (?) v.2.99.6 does not show anything for SC 2.5 in the WCAG view, even though various rules are tested and shown in the Rule Categories view. The unified-diff file here fixes this issue (see images below), as well as other fixes:
• support for SC 2.5 showing in the side panel
• `<tr>`, `<td>`, `<th>` in data tables no longer being treated as widgets
• many spelling and grammar fixes to panel messages

[ainsp-udiff.txt](https://github.com/opena11y/ainspector-for-firefox/files/13895096/ainsp-udiff.txt)

<img width="432" alt="AInspector-2997-WCAG-view" src="https://github.com/opena11y/ainspector-for-firefox/assets/11621433/6b3a807c-ed43-4a6f-97fc-c754c3da9d65">
<img width="431" alt="AInspector-2997-WCAG25-view" src="https://github.com/opena11y/ainspector-for-firefox/assets/11621433/b9d3faa0-6086-4ab5-9bc9-19558b0936bb">

**Comment by jongund** [comment]
Thank you for reporting this issue, I will will into it and fix it in the next release.

**Comment by jongund** [comment]
@ozross 
I have fixed this for the next release, thanks so much in reporting the bug.
